openapi: 3.0.0
info:
  title: Idpass-Lite-Java-API
  description: Idpass-Lite-Java-API docs
  version: 1.0.0
  contact:
    email: francesco.orlando270@gmail.com
    name: Francesco
paths:
  /verifyQRcode:
    post:
      description: Use this API to verify yout QR code.
      requestBody:
        description: The QR code to verify with the face photo
        required: true
        content: 
          application/json:
            schema:
                $ref: '#/components/schemas/qrCodeAndFace'
      responses:
        '200':
          description: 200 response. Returns true if the outcome is positive, false otherwise. It returns also the anagraphic.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/verificationResponse' 
  /getCertificate:
    get:
      description: Use this API to get the Certificate
      responses:
        '200':
          description: 200 response. Returns the Certificate of the QR code.
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/myCertificateDTO'
  
  /generete:
    post:
      description: Use this API to create the QR code.
      parameters:
        - name: format
          in: query
          description: Format of the returned image (png, jpg, svg).
          required: true
          schema:
            type: string
            enum: [png, jpg, svg]
      requestBody:
        description: QR code created successfully
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/myIdent'
      responses:
        '200':
          description: 200 response. Returns an image based on the specified format.
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpg:
              schema:
                type: string
                format: binary
            image/svg:
              schema:
                type: string
                format: binary
components:
  schemas:
    myIdent:
      type: object
      properties:
        photo:
          type: string
          format: binary
        given_name:
          type: string
        surname:
          type: string
        pin:
          type: string
        date_of_birth:
          type: string
          format: date
        sex:
          type: string
          enum: [F, M]
        nationality:
          type: string
        date_of_issue:
          type: string
          format: date
        date_of_expiry:
          type: string
          format: date
        id:
          type: string
        ss_number:
          type: string
      required:
        - photo
        - given_name
        - surname
        - pin
        - date_of_birth
        - sex
        - nationality
        - date_of_issue
        - date_of_expiry
        - id
        - ss_number
    myCertificateDTO:
      type: object
      properties:
        rootkey:
          type: string
        rootcert:
          type: string
        rootcerts:
          type: string
        childcert:
          type: string
        certchain:
          type: string
        signaturekey:
          type: string
        publicVerificatonKey:
          type: string
        encryptionKey:
          type: string
      required:
        - rootkey
        - given_name
        - surname
        - pin
        - date_of_birth
        - sex
        - nationality
        - date_of_issue
        - date_of_expiry
        - id
        - ss_number
    qrCodeAndFace:
      type: object
      properties:
        qrCode:
          type: string
          format: binary
        face:
          type: string
          format: binary
      required:
        - qrCode
        - face
    verificationResponse:
      type: object
      properties:
        outcome:
          type: boolean
          description: Returns true if the outcome is positive, false otherwise.
        body:
          $ref: '#/components/schemas/myIdent'